table:
  name: commandcenter_reportconfiguration
  schema: public
configuration:
  column_config:
    border_color:
      custom_name: borderColor
    border_weight:
      custom_name: borderWeight
    default_docx_template_id:
      custom_name: docxTemplateId
    default_pptx_template_id:
      custom_name: pptxTemplateId
    enable_borders:
      custom_name: enableBorders
    label_figure:
      custom_name: labelFigure
    label_table:
      custom_name: labelTable
    prefix_figure:
      custom_name: prefixFigure
    prefix_table:
      custom_name: prefixTable
  custom_column_names:
    border_color: borderColor
    border_weight: borderWeight
    default_docx_template_id: docxTemplateId
    default_pptx_template_id: pptxTemplateId
    enable_borders: enableBorders
    label_figure: labelFigure
    label_table: labelTable
    prefix_figure: prefixFigure
    prefix_table: prefixTable
  custom_name: reportConfiguration
  custom_root_fields: {}
object_relationships:
  - name: docxTemplate
    using:
      foreign_key_constraint_on: default_docx_template_id
  - name: pptxTemplate
    using:
      foreign_key_constraint_on: default_pptx_template_id
select_permissions:
  - role: manager
    permission:
      columns:
        - border_color
        - border_weight
        - default_docx_template_id
        - default_pptx_template_id
        - enable_borders
        - id
        - label_figure
        - label_table
        - prefix_figure
        - prefix_table
      filter: {}
  - role: user
    permission:
      columns:
        - border_color
        - border_weight
        - default_docx_template_id
        - default_pptx_template_id
        - enable_borders
        - id
        - label_figure
        - label_table
        - prefix_figure
        - prefix_table
      filter: {}
update_permissions:
  - role: manager
    permission:
      columns:
        - border_color
        - border_weight
        - default_docx_template_id
        - default_pptx_template_id
        - enable_borders
        - label_figure
        - label_table
        - prefix_figure
        - prefix_table
      filter: {}
      check: {}
